### ISSUE TITLE
codingstyle-包名调整

### ISSUE THREAD

**Issue by shjborage** [Android-Guide/CalcApp#2]
我们现在有个 www.saick.net 的域名，现在只用了 blog.saick.net
我们可以给这个计算器开个类似这样的包名 : `net.saick.android.calcapp`

**Comment by shjborage** [comment]
包名请按这个标准提交。
https://github.com/shjborage/CodingStyle/blob/master/Java.md#521-%E5%8C%85%E5%91%BD%E5%90%8D

**Comment by rivenlx** [comment]
该项目是通过eclipse编写，所以通过eclipse工具更改包名
